### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9255]
We've received a new issue alert regarding exceeding a rate limit. We should inquire with the upstream and determine whether our rate limit needs adjustment or if a change in how we use the endpoint can reduce our rate. 

```
Common::Exceptions::BackendServiceException: BackendServiceException: {:detail=>{"message"=>"API rate limit exceeded"}, :code=>"VET360_AV_ERROR"}
/app/lib/va_profile/address_validation/service.rb:56:in `handle_error': BackendServiceException: {:detail=>{"message"=>"API rate limit exceeded"}, :code=>"VET360_AV_ERROR"} (Common::Exceptions::BackendServiceException)
	
from /app/lib/va_profile/address_validation/service.rb:42:in `rescue in candidate'
	
from /app/lib/va_profile/address_validation/service.rb:35:in `candidate'
```

[New issue slack alert](https://dsva.slack.com/archives/C06T6ABC9MX/p1722350902366169)
[Datadog](https://vagov.ddog-gov.com/apm/error-tracking/issue/db43d770-4e81-11ef-b743-da7ad0900007?query=%40issue.age%3A%3C%3D172800000%20env%3Aeks-prod%20resource_name%3AMobile%2A&view=spans&from_ts=1722178010000&to_ts=1722350810000&live=false)

**Comment by Tonksthebear** [comment]
Got the rate limit increased to 70req/s
